#!/bin/bash
#--------------------------------------------------
# This script is used for: 
# 1. to run feibor-ansible in a container (recommended)
# @author:   lipengfei
# @usage:    ./ansidown.sh
# @repo:     https://github.com/feibor/feibor-ansible
#--------------------------------------------------

set -o nounset
set -o errexit
set -o pipefail

source ./scripts/liblog.sh

EZANSI=1.0.1
EZANSI_PATH=/etc/ezansi
SSH_PATH=/root/.ssh

function run_ezansi_container() {
 start_feiboransible_docker
}

function start_feiboransible_docker() {

#   # get host's IP
#   host_if=$(ip route|grep default|head -n1|cut -d' ' -f5)
#   host_ip=$(ip a|grep "$host_if$"|head -n1|awk '{print $2}'|cut -d'/' -f1)

#   # If retrieval fails, prompt the user to input an IP address
#   if [ -z "$host_if" ]; then
#     read -p "Unable to retrieve the default gateway interface. Please enter an IP address: " host_if
#     echo "User input IP address: $"
#     # Further operations can be performed using the user input IP address here
#   else
#     info "Use default gateway interface: $host_if"
#     # Further operations can be performed using the default gateway interface here
#   fi

  # run kubeasz docker container

  info " docker run --detach \
      --name ezansi \
      --network host \
      --restart always \
      --volume $EZANSI_PATH:$EZANSI_PATH \
      --volume $SSH_PATH:/root/.ssh \
      --volume /etc/docker:/etc/docker \
      lipengfei217/ezansi:${EZANSI}
"
  docker run --detach \
    #   --env HOST_IP="$host_ip" \
      --name ezansi \
      --network host \
      --restart always \
      --volume $EZANSI_PATH:$EZANSI_PATH \
      --volume $SSH_PATH:/root/.ssh \
      --volume /etc/docker:/etc/docker \
      lipengfei217/ezansi:${EZANSI}
   docker exec ezansi install -o root -g root $BASE/ansictl /usr/bin
}

function main() {
    BASE="$EZANSI_PATH"
    imageDir="$BASE/down/images"
    ctrImageDir="$BASE/down/ctrimages"
    # check if use bash shell
    # readlink /proc/$$/exe|grep -q "bash" || { logger error "you should use bash shell, not sh"; exit 1; }
    # check if use with root
    # [[ "$EUID" -ne 0 ]] && { logger error "you should run this script as root"; exit 1; }

    ACTION=""
    while getopts "CDP:RSX:d:e:k:m:z:" OPTION; do
        case "$OPTION" in
            R)
            ACTION="run_ezansi_container"
            ;;
            ?)
            echo "Error action"
            exit 1
            ;;
        esac
    done
    
    [[ "$ACTION" == "" ]] && { error "illegal option"; exit 1; }
        
    # excute cmd "$ACTION" 
    info "Action begin: $ACTION"
    ${ACTION} || { error "Action failed: $ACTION"; return 1; }
    info "Action successed: $ACTION"
}
info "Start container"
main "$@"