#!/bin/bash
#--------------------------------------------------
# This script is used for: 
# 1. to run feibor-ansible in a container (recommended)
# @author:   lipengfei
# @usage:    ./ansidown.sh
# @repo:     https://github.com/feibor/feibor-ansible
#--------------------------------------------------

set -o nounset
set -o errexit
set -o pipefail

source ./scripts/liblog.sh
source ./scripts/env.sh

EZANSI_CONTAINER_NAME="feiboransi"


function usage() {
    echo -e "\033[33mUsage:\033[0m ezctl COMMAND [args]"
    cat <<EOF
-------------------------------------------------------------------------------------
flags:
    -S            to start $EZANSI_BASE_PATH docker container.
Use "ezansictl <command>" for more information. 
EOF
}

function run_ezansi_container() {
 start_feiboransible_docker
}

function start_feiboransible_docker() {
  # run kubeasz docker container
  commandlog "docker run --detach \
      --name $EZANSI_CONTAINER_NAME \
      --network host \
      --restart always \
      --env EZANSI_BASE_PATH=$EZANSI_BASE_PATH \
      --volume $EZANSI_BASE_PATH:$EZANSI_BASE_PATH \
      --volume $EZANSI_MATERIALS_PATH:/data/99.Deployment_Materials \
      --volume $SSH_PATH:/root/.ssh \
      --volume /etc/docker:/etc/docker \
      lipengfei217/ezansi:${EZANSI}"

  docker run --detach \
      --name $EZANSI_CONTAINER_NAME \
      --network host \
      --restart always \
      --env EZANSI_BASE_PATH=$EZANSI_BASE_PATH \
      --volume $EZANSI_BASE_PATH:$EZANSI_BASE_PATH \
      --volume $EZANSI_MATERIALS_PATH:/data/99.Deployment_Materials \
      --volume $SSH_PATH:/root/.ssh \
      --volume /etc/docker:/etc/docker lipengfei217/ezansi:${EZANSI}

  commandlog "docker exec $EZANSI_CONTAINER_NAME install -o root -g root $EZANSI_BASE_PATH/ezansictl /usr/bin"
  docker exec $EZANSI_CONTAINER_NAME chmod +x $EZANSI_BASE_PATH/ezansictl
  docker exec $EZANSI_CONTAINER_NAME ln -s $EZANSI_BASE_PATH/ezansictl /usr/bin
  docker exec $EZANSI_CONTAINER_NAME ln -s $EZANSI_BASE_PATH/scripts /usr/bin
}

function main() {
    imageDir="$EZANSI_BASE_PATH/down/images"
    ctrImageDir="$EZANSI_BASE_PATH/down/ctrimages"
    # check if use bash shell
    # readlink /proc/$$/exe|grep -q "bash" || { logger error "you should use bash shell, not sh"; exit 1; }
    # check if use with root
    # [[ "$EUID" -ne 0 ]] && { logger error "you should run this script as root"; exit 1; }
    ACTION=""
    while getopts "CDP:RSX:d:e:k:m:z:" OPTION; do
        case "$OPTION" in
            S)
                ACTION="run_ezansi_container"
                ;;
            (*)
                usage
                exit 0
                ;;
        esac
    done
    
    [[ "$ACTION" == "" ]] && { error "illegal option"; usage ;exit 1; }
        
    # excute cmd "$ACTION" 
    info "Action begin: $ACTION"
    ${ACTION} || { error "Action failed: $ACTION"; return 1; }
    info "Action successed: $ACTION"
}
info "Start container"
main "$@"