- name: Send the materials of redis-standalone deployment to destination.{{redis_dest_dir}}/
  copy:
    src: "{{redis_base_dir}}/3.redis-sentinel/"
    dest: "{{redis_dest_dir}}/"
    backup: true
    
- name: Send the images to destination. 
  copy: 
    src: "{{redis_image_dir}}"
    dest: "{{redis_dest_dir}}/images/"
    backup: false

- name: Send the start, stop, restart &etc. scripts to destination. 
  copy: 
    src: "{{redis_base_dir}}/99.scripts/"
    dest: "{{redis_dest_dir}}"
    mode: u+rwx,g+rwx,o=r
    backup: false

- name: Use docker command to load images that located in {{server_name}}
  ansible.builtin.shell: |
    docker load -i {{redis_dest_dir}}/images/{{redis_image_file_name}}

- name: Update redis configurations {{server_name}} 
  ansible.builtin.shell: |
    sed -i 's/__server_name__/{{server_name}}/g' {{redis_dest_dir}}/docker-compose.yml
    sed -i 's/__host_redis_port__/{{host_redis_port}}/g' {{redis_dest_dir}}/docker-compose.yml
    sed -i 's#__redisconf_mount_path__#{{redis_conf_mount}}#g' {{redis_dest_dir}}/docker-compose.yml
    sed -i 's#__data_mount__#{{redis_data_mount}}#g' {{redis_dest_dir}}/docker-compose.yml
    sed -i 's#__redis_image_tag__#{{redis_image_tag}}#g' {{redis_dest_dir}}/docker-compose.yml

    sed -i 's/__master_cluster_name__/{{master_cluster_name}}/g' {{redis_dest_dir}}/config/redis.conf
    sed -i 's/__redis_masterauth__/{{redis_masterauth}}/g' {{redis_dest_dir}}/config/redis.conf
    sed -i 's/__redis_master_ip__/{{redis_master_ip}}/g' {{redis_dest_dir}}/config/redis.conf
    sed -i 's/__redis_master_port__/{{redis_master_port}}/g' {{redis_dest_dir}}/config/redis.conf
    sed -i 's/__at_least_agree_num__/{{at_least_agree_num}}/g' {{redis_dest_dir}}/config/redis.conf
    sed -i 's/__host_redis_port__/{{host_redis_port}}/g' {{redis_dest_dir}}/config/redis.conf

    sed -i 's/__sentinel_announce_ip__/{{sentinel_announce_ip}}/g' {{redis_dest_dir}}/config/redis.conf
    sed -i 's/__sentinel_announce_port__/{{sentinel_announce_port}}/g' {{redis_dest_dir}}/config/redis.conf
    
- name: Start Redis compose {{server_name}} 
  ansible.builtin.shell: |
    cd {{redis_dest_dir}}
    sh {{redis_dest_dir}}/start.sh
