- name: Synchronize directories
  # file: name={{ item }} state=directory
  synchronize: 
    mode: push
    src: "{{ base_material_dir }}/2.middleware/1.redis-templates" 
    dest: "{{ middleware_dir }}/setup_template"

- name: Use ctr command to load images located in {{middleware_dir}}/setup_template/1.redis-templates
  ansible.builtin.shell: |
    cd {{middleware_dir}}/setup_template/1.redis-templates
    ls -l